# Generated by Django 2.0.5 on 2018-05-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Actual subtitle when within series. Do not forget the X when this is your only title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Event details like what is included or not', verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('url', models.CharField(blank=True, help_text='Can be left blank if event is part of a series, then value of series will be used.', max_length=100, verbose_name='Url')),
                ('email', models.CharField(blank=True, help_text='Can be left blank if event is part of a series, then value of series will be used.', max_length=100, verbose_name='E-mail address of game masters / organisation')),
                ('location_name', models.CharField(help_text='Name of the location, will be used as link text if url is also available', max_length=100, verbose_name='Location name')),
                ('location_url', models.CharField(blank=True, help_text='Url of location website', max_length=100, verbose_name='Location url')),
                ('location_info', models.TextField(help_text='Address and additional information about the location', verbose_name='Location information')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Series', verbose_name='Series this event is part of')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
