# Generated by Django 2.0.5 on 2018-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_links_user_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', help_text='Name of the event. Unique if this is a oneshot, name of the series plus a number if part of a series. Do not forget the X when this is your only title.', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, help_text='Actual subtitle when within series. Do not forget the X if the name does not contain it.', max_length=100, verbose_name='Title'),
        ),
    ]
