# Generated by Django 2.2.13 on 2020-06-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_created_updated_at_20200604_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_date',), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
