# Generated by Django 2.0.6 on 2018-06-30 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_change_event_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration timestamp'),
            preserve_default=False,
        ),
    ]
