# Generated by Django 2.2.13 on 2021-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_update_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admit_immediately',
            field=models.BooleanField(default=True, help_text='When checked, registrations are admitted immediately when finalized (subject to available slots), making the registration first come, first served. When unchecked, registrations are set to pending, to be admitted through some other process later (e.g. lottery or selection).', verbose_name='Admit registrations immediately (i.e. "first come, first served")'),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_mail_text',
            field=models.TextField(blank=True, help_text='Text to include in the registration confirmation e-mail for pending (e.g. lottery) registrations, explaining how admission works.', verbose_name='Mail text for pending registrations'),
        ),
    ]
