# Generated by Django 2.2.24 on 2021-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_pending_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_conditions',
            field=models.TextField(blank=True, help_text='These are shown in the list of conditions when finalizing a registration. Rendered inside the existing &lt;ul&gt; tag, so should contain &lt;li&gt; tags, but no &lt;ul&gt;.', verbose_name='Extra registration conditions'),
        ),
    ]
