# Generated by Django 2.0.5 on 2018-08-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.IntegerField(choices=[(0, 'Preparation in progress'), (1, 'Preparation complete'), (2, 'Registered'), (3, 'Waiting list'), (4, 'Cancelled')], verbose_name='Status'),
        ),
    ]
