# Generated by Django 2.2.24 on 2021-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_extra_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, help_text='At this time registration closes again. When empty, registration closes on the start date.', null=True, verbose_name='Registration closes at'),
        ),
    ]
