# Generated by Django 2.2.7 on 2019-11-08 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        ('events', '0006_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(through='registrations.Registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
