# Generated by Django 2.2.24 on 2022-02-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('events', '0007_event_registration_closes_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_group',
            field=models.ForeignKey(blank=True, help_text='Group of users that can view all information about this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Organizer group'),
        ),
    ]
