# Generated by Django 2.2.7 on 2019-11-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191108_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False, help_text='When checked, the event is visible to users. If registration is not open yet, they can prepare a registration already.', verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, help_text='At this time registration is open for everyone.', null=True, verbose_name='Registration opens at'),
        ),
    ]
