# Generated by Django 2.2.24 on 2022-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_organizer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signature_place',
            field=models.CharField(blank=True, help_text='Place to be prefilled in registration form for signature place.', max_length=100, verbose_name='Signature place'),
        ),
    ]
