# Generated by Django 2.2.7 on 2020-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_allow_more_blanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.IntegerField(blank=True, help_text='Maximum number of attendees for this event. If omitted, no there is no limit.', null=True),
        ),
    ]
