# Generated by Django 2.2.24 on 2022-02-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_signature_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra_conditions',
            field=models.TextField(blank=True, help_text='These are shown in the list of conditions when finalizing a registration. Rendered inside the existing &lt;ul&gt; tag, so should contain &lt;li&gt; tags, but no &lt;ul&gt;. Can use class=&quot;hide-on-form&quot; to show during online registration, but not on the paper form.', verbose_name='Extra registration conditions'),
        ),
    ]
