# Generated by Django 2.2.10 on 2020-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_add_slots'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['public', 'start_date'], name='idx_public_start_date'),
        ),
    ]
