# Generated by Django 2.2.24 on 2022-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_update_event_extra_conditions_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_change_until',
            field=models.DateField(blank=True, help_text='Registrations for this event can be changed until (including) this date. If empty, registrations cannot be changed. This includes all registration details, including options, personal details, etc.', null=True),
        ),
    ]
