# Generated by Django 2.2.24 on 2022-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_add_allow_change_until'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, email=''), models.Q(_negated=True, series=None), _connector='OR'), name='has_email_or_series'),
        ),
    ]
