# Generated by Django 2.2.24 on 2023-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_add_has_email_or_series_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False, help_text='When checked and a open date is set, the event is visible to users. If registration is not open yet, they can preview or (when admit_immediately is set) prepare a registration already.', verbose_name='Public'),
        ),
    ]
