# Generated by Django 2.2.12 on 2020-06-04 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='artauser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artauser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update timestamp'),
        ),
    ]
