# Generated by Django 2.2.24 on 2021-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_add_created_updated_at_20200604_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artauser',
            name='consent_announcements',
            field=models.BooleanField(default=False, help_text='You will receive at most a few e-mails each year.', verbose_name='Send me updates about new events'),
        ),
    ]
