# Generated by Django 2.0.5 on 2018-05-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Name of contact')),
                ('relation', models.CharField(help_text='For example: parent, partner, friend etc.', max_length=100, verbose_name='Relation to contact')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone number of contact')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'contacts',
                'verbose_name': 'contact',
            },
        ),
    ]
