# Generated by Django 2.0.5 on 2018-08-24 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_allergies', models.TextField(blank=True, help_text='Please specify any allergies that our kitchen staff should take into account. Please also mention the severity. Leave blank when you have no allergies.', null=True, verbose_name='Food allergies')),
                ('event_risks', models.TextField(blank=True, help_text='Please specify any medical or psychological conditions that we should take into account while preparing for the event. For example if you are allergic to smoke machines, can not handle flashes of light, are claustrophobic etc.', null=True, verbose_name='Take into account for event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medical details',
                'verbose_name_plural': 'medical details',
            },
        ),
    ]
