# Generated by Django 2.2.24 on 2021-09-29 20:10

from django.db import migrations, models

def set_default_nl(apps, schema_editor):
    apps.get_model("people", "artauser").objects.update(consent_announcements_nl=models.F('consent_announcements_en'))

def reverse_default_nl(apps, schema_editor):
    # This allows reversing when all consent is still equal for en/nl (i.e. during testing), but refuses to throw away
    # data when people have differentiated their preferences
    mixed = apps.get_model("people", "artauser").objects.exclude(consent_announcements_nl=models.F('consent_announcements_en'))
    if mixed.count() > 0:
        raise Exception("Cannot reverse mixed nl/en consent")

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_artauser_consent_announcements_update_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artauser',
            old_name='consent_announcements',
            new_name='consent_announcements_en',
        ),
        migrations.AlterField(
            model_name='artauser',
            name='consent_announcements_en',
            field=models.BooleanField(default=False, help_text='These are announcements about our events where English is the primary language. You will receive at most a few e-mails each year.', verbose_name='Send me announcements about new international events'),
        ),
        migrations.AddField(
            model_name='artauser',
            name='consent_announcements_nl',
            field=models.BooleanField(default=False, help_text='These are announcements for our events where Dutch is the primary language. You will receive at most a few e-mails each year.', verbose_name='Send me announcements about new Dutch events'),
        ),
        migrations.RunPython(set_default_nl, reverse_code=reverse_default_nl),
    ]
