# Generated by Django 2.2.24 on 2022-04-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_artauser_split_consent_en_nl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artauser',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
