# Generated by Django 2.0.5 on 2019-11-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_medicaldetails'),
        ('people', '0004_remove_username'),
    ]

    operations = [
    ]
