# Generated by Django 2.2.24 on 2022-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_artauser_set_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='event_risks',
            field=models.TextField(blank=True, help_text='Please specify any medical or psychological conditions that we should take into account while preparing for the event. For example if you are allergic to smoke machines, cannot handle flashes of light, are claustrophobic etc. Leave blank when there is nothing to mention.', verbose_name='Take into account for event'),
        ),
    ]
