# Generated by Django 2.2.7 on 2020-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_merge_20191107_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='artauser',
            name='consent_announcements',
            field=models.BooleanField(default=False, help_text='Keep me updated about new events. You will receive at most a few e-mails each year', verbose_name='Send updates'),
        ),
    ]
