# Generated by Django 2.2.7 on 2020-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_artauser_consent_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(help_text='For example: parent, partner, friend, etc.', max_length=100, verbose_name='Relation to contact'),
        ),
    ]
