# Generated by Django 2.2.7 on 2020-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_change_relation_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
