# Generated by Django 2.2.7 on 2020-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_make_emergency_contact_remarks_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(help_text='This should include a country code, e.g. +316987654321', max_length=100, verbose_name='Phone number of contact'),
        ),
    ]
