# Generated by Django 2.2.7 on 2020-02-16 16:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_convert_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
