# Generated by Django 2.2.7 on 2020-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_make_address_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(blank=True, help_text='For example: parent, partner, friend, etc.', max_length=100, verbose_name='Relation to contact'),
        ),
    ]
