# Generated by Django 2.2.10 on 2020-02-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_make_emergency_contact_relation_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='event_risks',
            field=models.TextField(blank=True, help_text='Please specify any medical or psychological conditions that we should take into account while preparing for the event. For example if you are allergic to smoke machines, can not handle flashes of light, are claustrophobic etc. Leave blank when there is nothing to mention.', null=True, verbose_name='Take into account for event'),
        ),
    ]
