# Generated by Django 2.2.10 on 2020-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_change_helptext_eventrisks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, verbose_name='City of residence'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalcode',
            field=models.CharField(blank=True, help_text='Optional', max_length=10, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(blank=True, help_text='Optional. For example: parent, partner, friend, etc.', max_length=100, verbose_name='Relation to contact'),
        ),
    ]
