# Generated by Django 2.2.10 on 2020-03-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_add_helptexts_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='food_allergies',
            field=models.TextField(blank=True, help_text='Please specify any allergies that our kitchen staff should take into account. Please also mention the severity. Do not use this field for food you dislike, only enter things that can cause real problems. Leave blank when you have no allergies. ', null=True, verbose_name='Food allergies'),
        ),
    ]
