# Generated by Django 2.2.10 on 2020-04-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_change_helptext_food_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='event_risks',
            field=models.TextField(blank=True, default='', help_text='Please specify any medical or psychological conditions that we should take into account while preparing for the event. For example if you are allergic to smoke machines, can not handle flashes of light, are claustrophobic etc. Leave blank when there is nothing to mention.', verbose_name='Take into account for event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='food_allergies',
            field=models.TextField(blank=True, default='', help_text='Please specify any allergies that our kitchen staff should take into account. Please also mention the severity. Do not use this field for food you dislike, only enter things that can cause real problems. Leave blank when you have no allergies. ', verbose_name='Food allergies'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='medicaldetails',
            constraint=models.CheckConstraint(check=models.Q(('event_risks', ''), ('food_allergies', ''), _negated=True), name='medical_details_not_empty'),
        ),
    ]
