# Generated by Django 2.2.10 on 2020-04-11 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_constrain_medical_details_non_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
