# Generated by Django 2.2.10 on 2020-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_rename_medical_details_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='remarks',
            field=models.CharField(blank=True, help_text='Optional. For example: Only call if #1 cannot be reached', max_length=200, verbose_name='Remarks'),
        ),
    ]
