language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

services:

env:

install:
  - pip install pipenv
    # This should really be sync instead of install, but that doesn't
    # have --system: https://github.com/pypa/pipenv/issues/2227
  - pipenv install --system --ignore-pipfile --deploy --dev

script:
  - make flake8
  - make check
  - make test

after_success:
  - coverage report -m
