language: python
python:
  - "3.7"

services:

env:

install:
  - pip install poetry
  - poetry install -n

script:
  - poetry run make flake8
  - poetry run make check
  - poetry run make test

after_success:
  - poetry run coverage report -m
