# Generated by Django 2.2.7 on 2020-02-09 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import konst.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0010_make_price_monetaryfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', konst.models.fields.ConstantChoiceField(choices=[(0, 'CONSENTED'), (1, 'WITHDRAWN')])),
                ('consent_name', models.CharField(help_text='Internal name for this consent', max_length=32, verbose_name='Consent for')),
                ('consent_description', models.CharField(help_text='What has the user agreed to exactly?', max_length=255, verbose_name='Consent description')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
