# Generated by Django 2.2.12 on 2020-04-13 21:17

from django.db import migrations, models
import konst.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', konst.models.fields.ConstantChoiceField(choices=[(0, 'CONSENTED'), (1, 'WITHDRAWN')])),
                ('consent_name', models.CharField(help_text='Internal name for this consent', max_length=32, verbose_name='Consent for')),
                ('consent_description', models.CharField(help_text='What has the user agreed to exactly?', max_length=255, verbose_name='Consent description')),
            ],
        ),
    ]
