# Generated by Django 2.2.7 on 2019-11-08 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('events', '0007_auto_20191108_2215'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('field_type', models.CharField(choices=[('choice', 'Choice'), ('string', 'String')], max_length=10)),
                ('allow_change_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'registration field',
                'verbose_name_plural': 'registration fields',
            },
        ),
        migrations.CreateModel(
            name='RegistrationFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('slots', models.IntegerField(blank=True, null=True)),
                ('full', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('depends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.RegistrationFieldOption')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='registrations.RegistrationField')),
                ('invite_only', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
            ],
            options={
                'verbose_name': 'registration field option',
                'verbose_name_plural': 'registration field options',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='RegistrationFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.RegistrationField')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.RegistrationFieldOption')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Registration')),
            ],
            options={
                'verbose_name': 'registration field value',
                'verbose_name_plural': 'registration field values',
            },
        ),
        migrations.AddField(
            model_name='registrationfield',
            name='depends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.RegistrationFieldOption'),
        ),
        migrations.AddField(
            model_name='registrationfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fields', to='events.Event'),
        ),
        migrations.AddField(
            model_name='registrationfield',
            name='invite_only',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
