# Generated by Django 2.2.7 on 2019-11-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20191109_0023'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registrationfield',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_name_for_event'),
        ),
    ]
