# Generated by Django 2.2.7 on 2019-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20191109_0031'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, status=4), fields=('event', 'user'), name='one_registration_per_user_per_event'),
        ),
    ]
