# Generated by Django 2.2.13 on 2020-06-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_add_created_updated_at_20200604_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationfield',
            options={'ordering': ('order', 'title'), 'verbose_name': 'registration field', 'verbose_name_plural': 'registration fields'},
        ),
    ]
