# Generated by Django 2.2.13 on 2020-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_update_meta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'status'], name='idx_event_status'),
        ),
    ]
