# Generated by Django 2.2.13 on 2021-08-17 15:58

from django.db import migrations, models
import konst
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registration_add_event_status_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='one_current_registration_per_user_per_event',
        ),
        migrations.RemoveConstraint(
            model_name='registration',
            name='active_registration_has_timestamp',
        ),
        migrations.AddField(
            model_name='registrationfieldoption',
            name='admit_immediately',
            field=models.BooleanField(default=False, help_text='When checked, registrations that select this option are admitted immediately, bypassing any lottery or similar configured for the event. Has no effect effect when "admit immediately" is already set for the event.', verbose_name='Admit registrations immediately'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=konst.models.fields.ConstantChoiceField(choices=[(0, 'Preparation in progress'), (1, 'Preparation complete'), (2, 'Registered'), (3, 'Waiting list'), (4, 'Cancelled'), (5, 'Pending')], verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(status__in={konst.Constant(PREPARATION_IN_PROGRESS=0, label='Preparation in progress'), konst.Constant(PREPARATION_COMPLETE=1, label='Preparation complete'), konst.Constant(REGISTERED=2, label='Registered'), konst.Constant(WAITINGLIST=3, label='Waiting list'), konst.Constant(PENDING=5, label='Pending')}), fields=('event', 'user'), name='one_current_registration_per_user_per_event'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, status__in={konst.Constant(REGISTERED=2, label='Registered'), konst.Constant(WAITINGLIST=3, label='Waiting list'), konst.Constant(PENDING=5, label='Pending')}), ('registered_at__isnull', False), _connector='OR'), name='active_registration_has_timestamp'),
        ),
    ]
