# Generated by Django 2.2.13 on 2021-08-25 19:51

from django.db import migrations
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_add_pending_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfield',
            name='field_type',
            field=konst.models.fields.ConstantChoiceCharField(choices=[('choice', 'Choice'), ('string', 'String')], max_length=10),
        ),
    ]
