# Generated by Django 2.2.7 on 2019-11-13 20:07

from django.db import migrations
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20191109_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=konst.models.fields.ConstantChoiceField(choices=[(0, 'Preparation in progress'), (1, 'Preparation complete'), (2, 'Registered'), (3, 'Waiting list'), (4, 'Cancelled')], verbose_name='Status'),
        ),
    ]
