# Generated by Django 2.2.13 on 2021-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_order_fields_and_options_by_order_and_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationfield',
            name='help_text',
            field=models.TextField(blank=True, help_text='Can contain HTML'),
        ),
    ]
