# Generated by Django 2.2.7 on 2019-11-17 00:06

from django.db import migrations, models
import konst


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20191117_0036'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, status__in={konst.Constant(REGISTERED=2, label='Registered'), konst.Constant(WAITINGLIST=3, label='Waiting list')}), ('registered_at__isnull', False), _connector='OR'), name='active_registration_has_timestamp'),
        ),
    ]
