# Generated by Django 2.2.13 on 2021-08-27 13:29

from django.db import migrations
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_registrationfield_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfield',
            name='field_type',
            field=konst.models.fields.ConstantChoiceCharField(choices=[('section', 'Section'), ('choice', 'Choice'), ('string', 'String')], max_length=10),
        ),
    ]
