# Generated by Django 2.2.7 on 2020-02-05 21:53

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_constrain_registered_at_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfieldoption',
            name='price',
            field=apps.core.fields.MonetaryField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
