# Generated by Django 2.2.13 on 2021-08-28 09:28

from django.db import migrations
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_registrationfield_add_section_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationfieldvalue',
            options={'base_manager_name': 'objects', 'verbose_name': 'registration field value', 'verbose_name_plural': 'registration field values'},
        ),
        migrations.AlterField(
            model_name='registrationfield',
            name='field_type',
            field=konst.models.fields.ConstantChoiceCharField(choices=[('section', 'Section'), ('choice', 'Choice'), ('string', 'String'), ('checkbox', 'Checkbox')], max_length=10),
        ),
    ]
