# Generated by Django 2.2.10 on 2020-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_refactor_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', 'event', 'status', 'created_at'], name='idx_user_event_status_created'),
        ),
        migrations.AddIndex(
            model_name='registrationfieldvalue',
            index=models.Index(fields=['option', 'registration'], name='idx_option_registration'),
        ),
        migrations.AddIndex(
            model_name='registrationfieldvalue',
            index=models.Index(fields=['registration', 'option'], name='idx_registration_option'),
        ),
    ]
