# Generated by Django 2.2.24 on 2021-08-30 08:02

from django.db import migrations
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_registrationfield_add_checkbox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfield',
            name='field_type',
            field=konst.models.fields.ConstantChoiceCharField(choices=[('section', 'Section'), ('choice', 'Choice'), ('rating5', 'Rating (1-5)'), ('string', 'String'), ('checkbox', 'Checkbox')], max_length=10),
        ),
    ]
