# Generated by Django 2.2.24 on 2021-09-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_registrationfield_add_rating5_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfieldvalue',
            name='string_value',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
