# Generated by Django 2.2.24 on 2021-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_registrationfieldvalue_string_value_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfield',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
