# Generated by Django 2.2.24 on 2021-09-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_registrationfield_enlarge_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationfield',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
