# Generated by Django 2.2.24 on 2021-09-17 18:42

from django.db import migrations
import konst.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_registrationfield_add_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationfield',
            name='field_type',
            field=konst.models.fields.ConstantChoiceCharField(choices=[('section', 'Section'), ('choice', 'Choice'), ('rating5', 'Rating (1-5)'), ('string', 'String'), ('image', 'Image'), ('checkbox', 'Checkbox'), ('uncheckbox', 'Checkbox (checked by default)')], max_length=10),
        ),
    ]
