# Generated by Django 2.2.24 on 2022-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_registrationfield_allow_change_until_add_help_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrationfieldvalue',
            name='one_value_per_field_per_registration',
        ),
        migrations.AddField(
            model_name='registrationfieldvalue',
            name='active',
            field=models.BooleanField(default=True, help_text='Set to null when this value is replaced by a new value', null=True),
        ),
        migrations.AddIndex(
            model_name='registrationfieldvalue',
            index=models.Index(fields=['active', 'option', 'registration'], name='idx_active_option_registration'),
        ),
        migrations.AddIndex(
            model_name='registrationfieldvalue',
            index=models.Index(fields=['active', 'registration', 'option'], name='idx_active_registration_option'),
        ),
        migrations.AddConstraint(
            model_name='registrationfieldvalue',
            constraint=models.UniqueConstraint(fields=('registration', 'field', 'active'), name='one_active_value_per_field_per_registration'),
        ),
        migrations.AddConstraint(
            model_name='registrationfieldvalue',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, active=False), name='active_cannot_be_false'),
        ),
    ]
