# Generated by Django 2.2.24 on 2022-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_registrationfieldvalue_add_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationfield',
            name='is_kitchen_info',
            field=models.BooleanField(default=False, help_text='This field should appear in the kitchen info.'),
        ),
    ]
