# Generated by Django 2.2.24 on 2022-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_timestamps_remove_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mollie_id',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]
