# Generated by Django 2.2.24 on 2022-05-02 10:22

from django.db import migrations, models
import django.utils.timezone

PENDING=0

def forward(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    # For lack of more info, just use the timestamp as creation and update time.
    Payment.objects.all().update(created_at=models.F('timestamp'), updated_at=models.F('timestamp'))
    Payment.objects.filter(status=PENDING).update(timestamp=None)

def reverse(apps, schema_editor):
    # Originally, pending transactions (which now have no timestamp) would store the creation time in the timestamp.
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(timestamp=None).update(timestamp=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_add_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='Transaction date/time'),
        ),
        migrations.RunPython(forward, reverse),
    ]
